import './analytics.js';
import './public-i18n.js';
import { API_BASE } from './api-config.js';
import { shell } from './sports.js';

const host = document.querySelector('#running-dashboard');
const escapeHtml = value => String(value ?? '').replace(/[&<>'"]/g, char => ({ '&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;' }[char]));
const formatKm = value => `${new Intl.NumberFormat('id-ID', { maximumFractionDigits:2 }).format(value)} KM`;
const formatPace = seconds => { const minutes = Math.floor(seconds / 60); return `${minutes}:${String(seconds % 60).padStart(2, '0')} /KM`; };
const leader = (title, label, rows, value) => `<section class="running-leader"><header><small>RUNNING CLUB</small><h2>${title}</h2></header><ol>${rows.length ? rows.map((row, index) => `<li><b>${String(index + 1).padStart(2, '0')}</b><strong>${escapeHtml(row.name)}</strong><span>${value(row)}</span></li>`).join('') : '<li><strong>Belum ada data</strong></li>'}</ol></section>`;
const dateLabel = date => new Intl.DateTimeFormat('id-ID', { day:'2-digit', month:'short', timeZone:'Asia/Jakarta' }).format(new Date(`${date}T00:00:00+07:00`));
function chartMarkup(daily, metric = 'km') {
  const isKm = metric === 'km'; const values = daily.map(day => isKm ? day.totalKm : day.averagePaceSeconds); const maximum = Math.max(...values, 1); const width = 1000; const gap = 18; const barWidth = Math.max(26, Math.min(88, (width - 80 - gap * (daily.length - 1)) / daily.length)); const plotWidth = barWidth * daily.length + gap * (daily.length - 1); const offset = (width - plotWidth) / 2;
  const bars = daily.map((day, index) => { const value = values[index]; const height = Math.max(5, (value / maximum) * 154); const x = offset + index * (barWidth + gap); const y = 182 - height; const display = isKm ? formatKm(value) : formatPace(value); return `<g class="running-bar"><title>${escapeHtml(`${dateLabel(day.date)}: ${display} • ${day.activities} aktivitas`)}</title><rect x="${x.toFixed(1)}" y="${y.toFixed(1)}" width="${barWidth.toFixed(1)}" height="${height.toFixed(1)}" rx="7"/><text x="${(x + barWidth / 2).toFixed(1)}" y="${(y - 8).toFixed(1)}" text-anchor="middle">${isKm ? value.toFixed(1) : formatPace(value).replace(' /KM','')}</text><text x="${(x + barWidth / 2).toFixed(1)}" y="207" text-anchor="middle">${dateLabel(day.date)}</text></g>`; }).join('');
  return `<section class="running-chart-panel"><header class="running-chart-head"><div><small>TREN AKTIVITAS</small><h2>PERFORMA HARIAN</h2><p>${isKm ? 'Total jarak seluruh pelari setiap hari.' : 'Pace rata-rata per hari; angka lebih kecil berarti lebih cepat.'}</p></div><div class="chart-tabs" role="tablist" aria-label="Pilihan metrik grafik"><button type="button" class="${isKm ? 'active' : ''}" data-chart="km" role="tab" aria-selected="${isKm}">TOTAL KM</button><button type="button" class="${isKm ? '' : 'active'}" data-chart="pace" role="tab" aria-selected="${!isKm}">PACE RATA-RATA</button></div></header><div class="running-chart-scroll"><svg class="running-chart" viewBox="0 0 ${width} 220" role="img" aria-label="Grafik batang ${isKm ? 'total kilometer' : 'pace rata-rata'} per hari"><line x1="30" x2="970" y1="182" y2="182"/>${bars}</svg></div><footer>Arahkan kursor ke batang untuk melihat detail tanggal dan jumlah aktivitas.</footer></section>`;
}
function render(data) {
  const { summary, leaders, daily, runners } = data;
  host.innerHTML = `<header class="running-hero"><div><p class="running-kicker">BRIDGESTONE CUP BP 2026</p><h1>RUNNING DASHBOARD</h1></div><p>Pantau perjalanan setiap pelari, dari total jarak hingga pace terbaik dan konsistensi latihan.</p></header>
  <section class="running-summary"><article class="running-stat"><small>TOTAL JARAK</small><strong>${formatKm(summary.totalKm)}</strong><span>akumulasi seluruh aktivitas</span></article><article class="running-stat"><small>PELARI TERDAFTAR</small><strong>${summary.runners}</strong><span>pelari terdaftar</span></article><article class="running-stat"><small>AKTIVITAS</small><strong>${summary.activities}</strong><span>catatan lari tervalidasi</span></article></section>
  ${chartMarkup(daily)}
  <section class="running-leaders">${leader('KM TERBANYAK', 'Total KM', leaders.distance, row => formatKm(row.totalKm))}${leader('PACE TERCEPAT', 'Best pace', leaders.pace, row => formatPace(row.fastestPaceSeconds))}${leader('PELARI TERAJIN', 'Aktivitas', leaders.consistency, row => `${row.activities} AKTIVITAS`)}</section>
  <section class="running-table-panel"><header class="running-table-head"><h2>KLASEMEN PELARI</h2><input id="runner-search" class="running-search" type="search" placeholder="Cari nama pelari" aria-label="Cari nama pelari"></header><table class="running-table"><thead><tr><th>RANK</th><th>NAMA PELARI</th><th>TOTAL KM</th><th>PACE TERCEPAT</th><th>AKTIVITAS</th></tr></thead><tbody id="runner-rows">${tableRows(runners)}</tbody></table></section>`;
  document.querySelector('#runner-search').addEventListener('input', event => { const needle = event.target.value.trim().toLocaleLowerCase('id-ID'); document.querySelector('#runner-rows').innerHTML = tableRows(runners.filter(row => row.name.toLocaleLowerCase('id-ID').includes(needle))); });
  const bindChartTabs = () => document.querySelectorAll('[data-chart]').forEach(button => button.addEventListener('click', event => { document.querySelector('.running-chart-panel').outerHTML = chartMarkup(daily, event.currentTarget.dataset.chart); bindChartTabs(); }));
  bindChartTabs();
}
function tableRows(rows) { return rows.length ? rows.map((row, index) => `<tr><td>${String(index + 1).padStart(2, '0')}</td><td>${escapeHtml(row.name)}</td><td>${formatKm(row.totalKm)}</td><td>${formatPace(row.fastestPaceSeconds)}</td><td>${row.activities}</td></tr>`).join('') : '<tr><td colspan="5">Pelari tidak ditemukan.</td></tr>'; }
shell('Running', [{ id:'leaderboard', label:'Leaderboard' }], () => {});
fetch(`${API_BASE}/running/dashboard`).then(response => response.ok ? response.json() : Promise.reject()).then(payload => render(payload.data)).catch(() => { host.innerHTML = '<div class="running-empty">DASHBOARD RUNNING BELUM DAPAT DIMUAT</div>'; });
